//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetMobileWeb.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeSheetMobileWeb.Models.SiteResources", typeof(SiteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptable.
        /// </summary>
        public static string Acceptable {
            get {
                return ResourceManager.GetString("Acceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddTaskConfirmed {
            get {
                return ResourceManager.GetString("AddTaskConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Actual Overtime Work.
        /// </summary>
        public static string AOW {
            get {
                return ResourceManager.GetString("AOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while approving timesheets.
        /// </summary>
        public static string ApprovalError {
            get {
                return ResourceManager.GetString("ApprovalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Approval View.
        /// </summary>
        public static string ApprovalModeView {
            get {
                return ResourceManager.GetString("ApprovalModeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvals Done successfuly.
        /// </summary>
        public static string ApprovalSuccessful {
            get {
                return ResourceManager.GetString("ApprovalSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Assignment.
        /// </summary>
        public static string AssignementPrompt {
            get {
                return ResourceManager.GetString("AssignementPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Actual Work.
        /// </summary>
        public static string AW {
            get {
                return ResourceManager.GetString("AW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangePeriod {
            get {
                return ResourceManager.GetString("ChangePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Change.
        /// </summary>
        public static string ChangePeriodDone {
            get {
                return ResourceManager.GetString("ChangePeriodDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change View.
        /// </summary>
        public static string ChangeView {
            get {
                return ResourceManager.GetString("ChangeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Change.
        /// </summary>
        public static string ChangeViewDone {
            get {
                return ResourceManager.GetString("ChangeViewDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select View.
        /// </summary>
        public static string ChangeViewTitle {
            get {
                return ResourceManager.GetString("ChangeViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes that will be lost. Would you like to continue?.
        /// </summary>
        public static string ConfirmRecallSubmit {
            get {
                return ResourceManager.GetString("ConfirmRecallSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save changes without submitting them?.
        /// </summary>
        public static string ConfirmSave {
            get {
                return ResourceManager.GetString("ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to submit all changes?.
        /// </summary>
        public static string ConfirmSubmit {
            get {
                return ResourceManager.GetString("ConfirmSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Approval View :.
        /// </summary>
        public static string CurrentApprovalView {
            get {
                return ResourceManager.GetString("CurrentApprovalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Timesheet View:.
        /// </summary>
        public static string CurrentRowView {
            get {
                return ResourceManager.GetString("CurrentRowView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Task Updator View:.
        /// </summary>
        public static string CurrentTaskView {
            get {
                return ResourceManager.GetString("CurrentTaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Timesheet:.
        /// </summary>
        public static string CurrentTimesheet {
            get {
                return ResourceManager.GetString("CurrentTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected item is already in the list.
        /// </summary>
        public static string DuplicateTask {
            get {
                return ResourceManager.GetString("DuplicateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Date.
        /// </summary>
        public static string EmptyDate {
            get {
                return ResourceManager.GetString("EmptyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while passing the updates.
        /// </summary>
        public static string GenericUpdateError {
            get {
                return ResourceManager.GetString("GenericUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        public static string HomeMenuAddRow {
            get {
                return ResourceManager.GetString("HomeMenuAddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string HomeMenuAddTask {
            get {
                return ResourceManager.GetString("HomeMenuAddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheets.
        /// </summary>
        public static string HomeMenuPeriods {
            get {
                return ResourceManager.GetString("HomeMenuPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall/Delete.
        /// </summary>
        public static string HomeMenuRecallDelete {
            get {
                return ResourceManager.GetString("HomeMenuRecallDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        public static string HomeMenuTaskDetail {
            get {
                return ResourceManager.GetString("HomeMenuTaskDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string HomeMenuTasks {
            get {
                return ResourceManager.GetString("HomeMenuTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string HomeMenuTimeInput {
            get {
                return ResourceManager.GetString("HomeMenuTimeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet.
        /// </summary>
        public static string HomeMenuTimesheet {
            get {
                return ResourceManager.GetString("HomeMenuTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Row.
        /// </summary>
        public static string HomeMenuTimesheetDetail {
            get {
                return ResourceManager.GetString("HomeMenuTimesheetDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheets.
        /// </summary>
        public static string HomeMenuTimesheets {
            get {
                return ResourceManager.GetString("HomeMenuTimesheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet Mobile.
        /// </summary>
        public static string HomeShortTitle {
            get {
                return ResourceManager.GetString("HomeShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheets.
        /// </summary>
        public static string HomeTimesheets {
            get {
                return ResourceManager.GetString("HomeTimesheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.. Loading.
        /// </summary>
        public static string InitialLoadingMessage {
            get {
                return ResourceManager.GetString("InitialLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes that will be lost. Would you like to continue?.
        /// </summary>
        public static string LeaveApplication {
            get {
                return ResourceManager.GetString("LeaveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Classification.
        /// </summary>
        public static string LineClassification {
            get {
                return ResourceManager.GetString("LineClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait, loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvals.
        /// </summary>
        public static string MyApprovals {
            get {
                return ResourceManager.GetString("MyApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add N. Bill. Actual Work .
        /// </summary>
        public static string NBAW {
            get {
                return ResourceManager.GetString("NBAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add N.  Bill Overtime Work.
        /// </summary>
        public static string NBOW {
            get {
                return ResourceManager.GetString("NBOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Timesheet View.
        /// </summary>
        public static string NewRowView {
            get {
                return ResourceManager.GetString("NewRowView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task Updator View.
        /// </summary>
        public static string NewTaskView {
            get {
                return ResourceManager.GetString("NewTaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Timesheet.
        /// </summary>
        public static string NewTimesheet {
            get {
                return ResourceManager.GetString("NewTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Timesheet Selected.
        /// </summary>
        public static string NoPeriodSelected {
            get {
                return ResourceManager.GetString("NoPeriodSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose project.
        /// </summary>
        public static string ProjectPrompt {
            get {
                return ResourceManager.GetString("ProjectPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall.
        /// </summary>
        public static string Recall {
            get {
                return ResourceManager.GetString("Recall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to recall/delete the timesheet.
        /// </summary>
        public static string RecallMessage {
            get {
                return ResourceManager.GetString("RecallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Timesheet View:.
        /// </summary>
        public static string RowViewLabel {
            get {
                return ResourceManager.GetString("RowViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error whiel submitting the status, but staus changes were succesfully passed.
        /// </summary>
        public static string StatusSubmitError {
            get {
                return ResourceManager.GetString("StatusSubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating the status.
        /// </summary>
        public static string StatusUpdateError {
            get {
                return ResourceManager.GetString("StatusUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates Report.
        /// </summary>
        public static string TaskSummaryTitle {
            get {
                return ResourceManager.GetString("TaskSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task Updator View:.
        /// </summary>
        public static string TaskViewLabel {
            get {
                return ResourceManager.GetString("TaskViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        public static string TimesheetCommentsLabel {
            get {
                return ResourceManager.GetString("TimesheetCommentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet:.
        /// </summary>
        public static string TimesheetNameLabel {
            get {
                return ResourceManager.GetString("TimesheetNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 3 Months.
        /// </summary>
        public static string TimesheetsSets1 {
            get {
                return ResourceManager.GetString("TimesheetsSets1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next 6 M Last 3 M.
        /// </summary>
        public static string TimesheetsSets2 {
            get {
                return ResourceManager.GetString("TimesheetsSets2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 6 Months.
        /// </summary>
        public static string TimesheetsSets3 {
            get {
                return ResourceManager.GetString("TimesheetsSets3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 12 Months.
        /// </summary>
        public static string TimesheetsSets4 {
            get {
                return ResourceManager.GetString("TimesheetsSets4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created and In Progress.
        /// </summary>
        public static string TimesheetsSets5 {
            get {
                return ResourceManager.GetString("TimesheetsSets5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Timesheets.
        /// </summary>
        public static string TimesheetsSets6 {
            get {
                return ResourceManager.GetString("TimesheetsSets6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string TimesheetStatusLabel {
            get {
                return ResourceManager.GetString("TimesheetStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while submitting the timesheet, but timesheet updates were succesfully passed.
        /// </summary>
        public static string TimesheetSubmitError {
            get {
                return ResourceManager.GetString("TimesheetSubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet Summary.
        /// </summary>
        public static string TimesheetSummaryTitle {
            get {
                return ResourceManager.GetString("TimesheetSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating the timesheet.
        /// </summary>
        public static string TimesheetUpdateError {
            get {
                return ResourceManager.GetString("TimesheetUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Actual Work:.
        /// </summary>
        public static string TotalActualWorkLabel {
            get {
                return ResourceManager.GetString("TotalActualWorkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Non-Bill Work:.
        /// </summary>
        public static string TotalNonBillableLabel {
            get {
                return ResourceManager.GetString("TotalNonBillableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Ovt. Non-Bill Work:.
        /// </summary>
        public static string TotalOvertimeNonBillableLabel {
            get {
                return ResourceManager.GetString("TotalOvertimeNonBillableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Overtime Work:.
        /// </summary>
        public static string TotalOvertimeWorkLabel {
            get {
                return ResourceManager.GetString("TotalOvertimeWorkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string UnChecked {
            get {
                return ResourceManager.GetString("UnChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates saved succesfully.
        /// </summary>
        public static string UpdateSuccesfull {
            get {
                return ResourceManager.GetString("UpdateSuccesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string WorkTimeAssignement {
            get {
                return ResourceManager.GetString("WorkTimeAssignement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string WorkTimeProject {
            get {
                return ResourceManager.GetString("WorkTimeProject", resourceCulture);
            }
        }
    }
}
